### ISSUE TITLE
增加多账号批量执行和pushplus推送

### ISSUE THREAD

**Issue by 1wyy** [yuzaii/JsQndxx_Python#1]
搞到这里了
![image](https://user-images.githubusercontent.com/68886089/158927755-33e04e1c-2f4b-43f7-83ac-ccd72ece58a4.png)

**Comment by 1wyy** [comment]
不会搞，弄得本来是代码的，一提交就这样了

**Comment by yuzaii** [comment]
啥情况
建议更新最新代码





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1wyy ***@***.***&gt;
发送时间: 2022年3月18日 10:35
收件人: yuzaii/JsQndxx_Python ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yuzaii/JsQndxx_Python] 增加多账号批量执行和pushplus推送 (Issue #1)





 
不会搞，弄得本来是代码的，一提交就这样了

**Comment by 1wyy** [comment]
搞好了，在readme里加了使用说明，可以结合云函数实现全自动

**Comment by yuzaii** [comment]
好的 非常感谢 我一般都挂在我服务器上



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1wyy ***@***.***&gt;
发送时间: 2022年3月18日 11:52
收件人: yuzaii/JsQndxx_Python ***@***.***&gt;
抄送: 周鱼仔 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [yuzaii/JsQndxx_Python] 增加多账号批量执行和pushplus推送 (Issue #1)





 
搞好了，在readme里加了使用说明，可以结合云函数实现全自动
