### ISSUE TITLE
源码里有个人信息，还请注意

### ISSUE THREAD

**Issue by lixiang810** [yuzaii/JsQndxx_Python#3]
稍微提醒一下。大概可以趁现在 `push -f` 过去，把 commit 记录覆盖掉。

**Comment by yuzaii** [comment]
好的 感谢你

**Comment by lixiang810** [comment]
不是，你这样搞的话，commit 记录还在的，比如 https://github.com/yuzaii/JsQndxx_Python/commit/4bffdeb3f36a4cf85e08f302fb93bacd6c25425d 
可以上网搜一下怎么删 commit 记录，当然那些 fork 里面的记录就没办法了。

**Comment by yuzaii** [comment]
好吧 其实当我写这个脚本的时候注意到了个人信息可能会泄露 但是这个cookie泄露了其实也没有太大的关系的 我先尝试着看看自己能不能清除 如果不行的话就算了 最后还是要十分感谢你的提醒

**Comment by lixiang810** [comment]
泄露的当然不只 Cookie，而是还包括你的真实姓名、学院和班级。

**Comment by yuzaii** [comment]
好了好了 感谢你的提醒！
