### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by HK-bruc1** [yuzaii/JsQndxx_Python#5]
每个省的都可以实现吗？我们省是需要看一会视频的，

**Comment by yuzaii** [comment]
当前前脚本只适配江苏省，其他省的本人没有测试过。

**Comment by HK-bruc1** [comment]
谢谢大佬，我看你这个只是请求到具体的课程url链接就完事了，难道不需要看视频吗，只要请求到那个界面就有学习记录？

**Comment by HK-bruc1** [comment]
谢谢大佬，我看你这个只是请求到具体的课程url链接就完事了，难道不需要看视频吗，只要请求到那个界面就有学习记录？

**Comment by yuzaii** [comment]
反正我们省的是这样
