### ISSUE TITLE
无法获取userinfo

### ISSUE THREAD

**Issue by rdyan0053** [yuzaii/JsQndxx_Python#6]
使用s.get(url=loginurl, headers=headers)返回状态码为200，但返回内容显示”抱歉，出错了 请在微信客户端打开链接”，导致无法获取userinfo

**Comment by yuzaii** [comment]
您好，我猜您肯定是laravel_session不正确，所以才导致的。

**Comment by yuzaii** [comment]
我已将代码更新，可以试试最新版本，会有错误信息的提示

**Comment by rdyan0053** [comment]
之前我使用的夜神模拟器+httpcanary抓包，今天换了fiddler+电脑微信代理登录，换了UA和laravel_session，终于可以了，很感谢
